package pingfederate

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/hashicorp/vault/sdk/framework"
	"github.com/hashicorp/vault/sdk/logical"
)

type staticRoleEntry struct {
	Name           string        `json:"name"`
	ClientID       string        `json:"client_id"`
	TTL            time.Duration `json:"ttl,omitempty"`
	MaxTTL         time.Duration `json:"max_ttl,omitempty"`
	RotationPeriod time.Duration `json:"rotation_period,omitempty"`
	LastRotated    time.Time     `json:"last_rotated,omitempty"`
}

func pathStaticRoles(b *pingFederateBackend) []*framework.Path {
	return []*framework.Path{
		{
			Pattern: "static-roles/" + framework.GenericNameRegex("name"),
			DisplayAttrs: &framework.DisplayAttributes{
				OperationPrefix: "ping-federate",
			},
			Fields: map[string]*framework.FieldSchema{
				"name": {
					Type:        framework.TypeLowerCaseString,
					Description: "Name of the role.",
					Required:    true,
				},
				"client_id": {
					Type:        framework.TypeString,
					Description: "The PingFederate OAuth 2.0 client ID to manage.",
					Required:    true,
				},
				"ttl": {
					Type:        framework.TypeDurationSecond,
					Description: "Default TTL for credentials generated by this role.",
				},
				"max_ttl": {
					Type:        framework.TypeDurationSecond,
					Description: "Maximum TTL for credentials generated by this role.",
				},
				"rotation_period": {
					Type:        framework.TypeDurationSecond,
					Description: "How often to rotate the client secret, in seconds. If set, the secret will be automatically rotated on this schedule.",
				},
			},
			ExistenceCheck: b.staticRoleExistenceCheck,
			Operations: map[logical.Operation]framework.OperationHandler{
				logical.ReadOperation: &framework.PathOperation{
					Callback: b.staticRoleConfigReadOperation,
					Summary:  "Read a static role.",
					DisplayAttrs: &framework.DisplayAttributes{
						OperationSuffix: "static-role",
					},
				},
				logical.CreateOperation: &framework.PathOperation{
					Callback: b.staticRoleWriteOperation,
					Summary:  "Create or update a static role.",
					DisplayAttrs: &framework.DisplayAttributes{
						OperationSuffix: "static-role",
					},
				},
				logical.UpdateOperation: &framework.PathOperation{
					Callback: b.staticRoleWriteOperation,
					Summary:  "Create or update a static role.",
					DisplayAttrs: &framework.DisplayAttributes{
						OperationSuffix: "static-role",
					},
				},
				logical.DeleteOperation: &framework.PathOperation{
					Callback: b.staticRoleDeleteOperation,
					Summary:  "Delete a static role.",
					DisplayAttrs: &framework.DisplayAttributes{
						OperationSuffix: "static-role",
					},
				},
			},
			HelpSynopsis:    "Manage static roles for PingFederate credential generation.",
			HelpDescription: "Create, read, update, or delete static roles that map to PingFederate OAuth 2.0 clients.",
		},
		{
			Pattern: "static-roles/?$",
			DisplayAttrs: &framework.DisplayAttributes{
				OperationPrefix: "ping-federate",
			},
			Operations: map[logical.Operation]framework.OperationHandler{
				logical.ListOperation: &framework.PathOperation{
					Callback: b.staticRoleListOperation,
					Summary:  "List static roles.",
					DisplayAttrs: &framework.DisplayAttributes{
						OperationSuffix: "static-roles",
					},
				},
			},
			HelpSynopsis:    "List existing static roles.",
			HelpDescription: "List existing static roles by name.",
		},
		{
			Pattern: "static-creds/" + framework.GenericNameRegex("name"),
			DisplayAttrs: &framework.DisplayAttributes{
				OperationPrefix: "ping-federate",
			},
			Fields: map[string]*framework.FieldSchema{
				"name": {
					Type:        framework.TypeLowerCaseString,
					Description: "Name of the static role.",
					Required:    true,
				},
			},
			Operations: map[logical.Operation]framework.OperationHandler{
				logical.ReadOperation: &framework.PathOperation{
					Callback: b.staticCredsReadOperation,
					Summary:  "Retrieve a bearer token for a static role.",
					DisplayAttrs: &framework.DisplayAttributes{
						OperationSuffix: "static-credentials",
					},
				},
			},
			HelpSynopsis:    "Retrieve credentials for a static role.",
			HelpDescription: "Returns a bearer token from PingFederate for the OAuth 2.0 client associated with the named role.",
		},
	}
}

func (b *pingFederateBackend) staticRoleExistenceCheck(ctx context.Context, req *logical.Request, d *framework.FieldData) (bool, error) {
	name, ok := d.Get("name").(string)
	if !ok {
		return false, nil
	}
	entry, err := req.Storage.Get(ctx, "static-roles/"+name)
	if err != nil {
		return false, err
	}
	return entry != nil, nil
}

func (b *pingFederateBackend) staticRoleConfigReadOperation(ctx context.Context, req *logical.Request, d *framework.FieldData) (*logical.Response, error) {
	name, ok := d.Get("name").(string)
	if !ok {
		return logical.ErrorResponse("name is required"), nil
	}

	role, err := getStaticRole(ctx, req.Storage, name)
	if err != nil {
		return nil, err
	}
	if role == nil {
		return nil, nil
	}

	data := map[string]any{
		"name":      role.Name,
		"client_id": role.ClientID,
	}
	if role.TTL > 0 {
		data["ttl"] = int64(role.TTL.Seconds())
	}
	if role.MaxTTL > 0 {
		data["max_ttl"] = int64(role.MaxTTL.Seconds())
	}
	if role.RotationPeriod > 0 {
		data["rotation_period"] = int64(role.RotationPeriod.Seconds())
	}
	if !role.LastRotated.IsZero() {
		data["last_rotated"] = role.LastRotated.Format(time.RFC3339)
	}

	return &logical.Response{Data: data}, nil
}

func (b *pingFederateBackend) staticCredsReadOperation(ctx context.Context, req *logical.Request, d *framework.FieldData) (*logical.Response, error) {
	name, ok := d.Get("name").(string)
	if !ok {
		return logical.ErrorResponse("name is required"), nil
	}

	role, err := getStaticRole(ctx, req.Storage, name)
	if err != nil {
		return nil, err
	}
	if role == nil {
		return nil, nil
	}

	client, err := b.getClient(ctx, req.Storage)
	if err != nil {
		return nil, err
	}

	secret, err := client.GetClientSecret(ctx, role.ClientID)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve client secret for %s: %w", role.ClientID, err)
	}

	tokenResp, err := client.GetAccessToken(ctx, role.ClientID, secret)
	if err != nil {
		return nil, fmt.Errorf("failed to obtain access token for %s: %w", role.ClientID, err)
	}

	return &logical.Response{
		Data: map[string]any{
			"access_token": tokenResp.AccessToken,
			"token_type":   tokenResp.TokenType,
			"expires_in":   tokenResp.ExpiresIn,
		},
	}, nil
}

func (b *pingFederateBackend) staticRoleWriteOperation(ctx context.Context, req *logical.Request, d *framework.FieldData) (*logical.Response, error) {
	name, ok := d.Get("name").(string)
	if !ok {
		return logical.ErrorResponse("name is required"), nil
	}

	role, err := getStaticRole(ctx, req.Storage, name)
	if err != nil {
		return nil, err
	}
	if role == nil {
		role = &staticRoleEntry{Name: name}
	}

	if clientID, ok := d.GetOk("client_id"); ok {
		role.ClientID, _ = clientID.(string)
	}
	if v, ok := d.GetOk("ttl"); ok {
		if seconds, ok := v.(int); ok {
			role.TTL = time.Duration(int64(seconds) * int64(time.Second))
		}
	}
	if v, ok := d.GetOk("max_ttl"); ok {
		if seconds, ok := v.(int); ok {
			role.MaxTTL = time.Duration(int64(seconds) * int64(time.Second))
		}
	}
	if v, ok := d.GetOk("rotation_period"); ok {
		if seconds, ok := v.(int); ok {
			role.RotationPeriod = time.Duration(int64(seconds) * int64(time.Second))
		}
	}

	if role.ClientID == "" {
		return logical.ErrorResponse("client_id is required"), nil
	}

	if role.RotationPeriod > 0 && role.RotationPeriod < 60*time.Second {
		return logical.ErrorResponse("rotation_period must be at least 60 seconds"), nil
	}

	// Set last_rotated to now when rotation is first configured so the
	// periodic function knows when the next rotation is due.
	if role.RotationPeriod > 0 && role.LastRotated.IsZero() {
		role.LastRotated = time.Now()
	}

	entry, err := logical.StorageEntryJSON("static-roles/"+name, role)
	if err != nil {
		return nil, fmt.Errorf("failed to create storage entry: %w", err)
	}

	if err := req.Storage.Put(ctx, entry); err != nil {
		return nil, fmt.Errorf("failed to write role to storage: %w", err)
	}

	return nil, nil
}

func (b *pingFederateBackend) staticRoleDeleteOperation(ctx context.Context, req *logical.Request, d *framework.FieldData) (*logical.Response, error) {
	name, ok := d.Get("name").(string)
	if !ok {
		return logical.ErrorResponse("name is required"), nil
	}

	if err := req.Storage.Delete(ctx, "static-roles/"+name); err != nil {
		return nil, fmt.Errorf("failed to delete role from storage: %w", err)
	}

	return nil, nil
}

func (b *pingFederateBackend) staticRoleListOperation(ctx context.Context, req *logical.Request, _ *framework.FieldData) (*logical.Response, error) {
	roles, err := req.Storage.List(ctx, "static-roles/")
	if err != nil {
		return nil, fmt.Errorf("failed to list roles: %w", err)
	}

	return logical.ListResponse(roles), nil
}

func getStaticRole(ctx context.Context, s logical.Storage, name string) (*staticRoleEntry, error) {
	entry, err := s.Get(ctx, "static-roles/"+name)
	if err != nil {
		return nil, fmt.Errorf("failed to read role from storage: %w", err)
	}
	if entry == nil {
		return nil, nil
	}

	var role staticRoleEntry
	if err := json.Unmarshal(entry.Value, &role); err != nil {
		return nil, fmt.Errorf("failed to deserialize role: %w", err)
	}

	return &role, nil
}
